realm=yait.airdnd.co.uk
server-name=

listening-ip=0.0.0.0
external-ip=46.101.77.164

listening-port=3478
min-port=10000
max-port=20000

# Use fingerprint in TURN Message
fingerprint

log-file=/var/log/turnserver.log

# Enable verbose logging
verbose

user=test:test123

# Enable long term credential mechanism
lt-cred-mech

# SSL Certificates
cert=/etc/letsencrypt/live/yait.airdnd.co.uk/cert.pem
pkey=/etc/letsencrypt/live/yait.airdnd.co.uk/privkey.pem

tls-listening-port=443
