name: Deploy UI
run-name: Deploying UI to Prod
on: [push, workflow_dispatch]
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    container: node:21
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: Install rsync
        run: |
          apt-get update
          apt-get -y install rsync

      - name: Install Deps
        run: |
          npm install
          npm run build
        working-directory: ${{ github.workspace }}/app/
      - run: |
          ls
        working-directory: ${{ github.workspace }}/app/dist/app/browser

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{secrets.TARGET_SERVER}}
          remote-user: ${{secrets.REMOTE_USER}}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ${{ secrets.DESTINATION_PATH}}
          source-path: ${{ github.workspace }}/app/dist/app/browser/
