name: Deploy API
run-name: Deploying API to Prod
on:
  push:
    #paths: YetAnotherInitiativeTrackerAPI/**
  workflow_dispatch:
jobs:
  Deploy-API:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 🧱 Install Deps
        run: |
          apt-get update
          apt-get -y install rsync
          apt-get -y install openssh-client
        working-directory: ${{ github.workspace }}/app/

      - name: 🏗 Build
        run: |
          dotnet publish --runtime linux-x64 --configuration Release --self-contained
        working-directory: ${{ github.workspace }}/YetAnotherInitiativeTrackerAPI/

      - name: 🔐 Prepping Keys
        run: |
          pwd
          mkdir /.ssh    
          touch /.ssh/yait_ssh_key
          echo "${{ secrets.SSH_KEY }}" > /.ssh/yait_ssh_key
          chmod --recursive 700 /.ssh
          ls -l /.ssh
          md5sum /.ssh/yait_ssh_key
        working-directory: ${{ github.workspace }}

      - name: ⬆ Uploading to Server
        run: >
          rsync 
          -e "
          ssh -p 22 
          -i /.ssh/yait_ssh_key 
          -o StrictHostKeyChecking=no" 
          --archive 
          --verbose 
          --compress 
          --human-readable 
          --progress 
          --delete-after ./* ${{secrets.REMOTE_USER}}@${{secrets.TARGET_SERVER}}:${{ secrets.API_DESTINATION_PATH}}
        working-directory: ${{ github.workspace }}/YetAnotherInitiativeTrackerAPI/bin/Release/net8.0/linux-x64/publish

      - name: 🔄 Restart Service
        run: >
          ssh -p 22 
          -i /.ssh/yait_ssh_key 
          -o StrictHostKeyChecking=no
          ${{secrets.REMOTE_USER}}@${{secrets.TARGET_SERVER}} 
          "restart-yait-api"
        working-directory: ${{ github.workspace }}/YetAnotherInitiativeTrackerAPI/bin/Release/net8.0/linux-x64/publish
